apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: naive_dice
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4000
      name: http
    - port: 443
      targetPort: 4000
      name: https
  selector:
    app: naive_dice
