use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :naive_dice, NaiveDiceWeb.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [host: "${HOST}", scheme: "https", port: 443],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  secret_key_base: "${SECRET_KEY_BASE}"

config :naive_dice, NaiveDice.Repo,
  username: "${DATABASE_USERNAME}",
  password: "${DATABASE_PASSWORD}",
  database: "${DATABASE_DB}",
  hostname: "${DATABASE_HOST}",
  port: "${DATABASE_PORT}",
  show_sensitive_data_on_connection_error: false,
  pool_size: System.get_env("POOL_SIZE") || 20

config :naive_dice, Stripe,
  api_key: "${STRIPE_API_KEY}",
  public_key: "${STRIPE_PUBLIC_KEY}"

config :logger, level: :info
